# inherit_from: .rubocop_todo.yml
require:
  - rubocop-rails
  # - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6.5
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/**'
    - 'lib/tasks/*'
    - 'node_modules/**/*'
  NewCops: disable

Documentation:
  Enabled: false

Rails:
  Enabled: true

# Warnings at application launch (Rails.logger not defined yet)
Rails/Output:
  Exclude:
    - 'config/application.rb'
    - 'config/initializers/*.rb'
    - 'db/seeds.rb'

Layout/HeredocIndentation:
  Enabled: false

Layout/ParameterAlignment:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/IndentationConsistency:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Layout/Tab:
  Enabled: false

Layout/LineLength:
  Max: 160
  Exclude:
    - 'app/admin/blog_posts.rb'
    - 'app/admin/dashboard.rb'
    - 'app/admin/tranxactions.rb'
    - 'Gemfile'

Lint/RescueException:
  Exclude:
    - 'config/application.rb'

Metrics/MethodLength:
  Max: 40

Metrics/ClassLength:
  Max: 200

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'app/**/concerns/*.rb'
    - 'config/routes.rb'
    - 'app/admin/*'

Metrics/AbcSize:
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/ParameterLists:
  Max: 5
  Exclude:
    - app/models/tranxaction.rb

Rails/ApplicationJob:
  Enabled: false

Rails/ApplicationRecord:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/OutputSafety:
  Exclude:
    - app/admin/blog_posts.rb
    - app/admin/tools.rb
    - app/admin/tranxactions.rb

Rails/UniqueValidationWithoutIndex:
  Exclude:
    - app/models/tax_category.rb
    - app/models/trade_pair.rb

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - config/application.rb

Style/Documentation:
  Exclude:
    - 'config/application.rb'

Style/MixinUsage:
  Exclude:
    - 'db/seeds.rb'

Style/RegexpLiteral:
  EnforcedStyle: mixed
  AllowInnerSlashes: true
