//= require application
//= require sinon

beforeEach(module('app'));

beforeEach(inject(function(_$httpBackend_, _$compile_, $rootScope, $controller, $location, $injector, _$timeout_, _$q_, _$window_, _$state_, _$stateParams_, _$filter_) {
  $filter = _$filter_;
  $scope = $rootScope.$new();
  this.http = _$httpBackend_;
  this.compile = _$compile_;
  this.location = $location;
  this.controller = $controller;
  this.injector = $injector;
  $state = _$state_;
  $stateParams = _$stateParams_;
  $timeout = _$timeout_;
  $q = _$q_;
  $window = _$window_;
  this.model = (function(_this) {
    return function(name) {
      return _this.injector.get(name);
    };
  })(this);
  this.eventLoop = {
    flush: (function(_this) {
      return function() {
        return _this.scope.$digest();
      };
    })(this)
  };
  return sandbox = sinon.sandbox.create();
}));

afterEach(function() {
  sandbox.restore();

  this.http.resetExpectations();
  return this.http.verifyNoOutstandingExpectation();
});

// ---
// generated by coffee-script 1.9.2