---
development:
  cloud_name: hpxlnqput
  api_key: '121531647547298'
  api_secret: eSXzTIQI29kgeI47azXdv2sO85M
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: hpxlnqput
  api_key: '121531647547298'
  api_secret: eSXzTIQI29kgeI47azXdv2sO85M
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: hpxlnqput
  api_key: '121531647547298'
  api_secret: eSXzTIQI29kgeI47azXdv2sO85M
  enhance_image_tag: true
  static_file_support: false
